apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: postgres-secret-csi
spec:
  provider: azure
  secretObjects:
    - secretName: pgpassword    
      type: Opaque              
      data:
      - objectName: PGPASSWORD
        key: PGPASSWORD
  parameters:
    keyvaultName: kv37107-shmakseslu 
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "92dc2140-85d1-4312-962f-ca114377d64a" # the client ID of the MSI  
    cloudName: ""                         
    objects:   |
      array:
        - |
          objectName: PGPASSWORD       
          objectType: secret              
          objectVersion: ""               
    tenantId: "b7926b94-54b3-4d1c-9dac-ac9296ebe33b"
  
